version: '3.9'
services:
  api:
    image: node:18-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: sh -c "cd apps/api && npm install && npm run dev"
    ports:
      - "3333:3000"
  web:
    image: node:18-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: sh -c "cd apps/web && npm install && npm run dev -- --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080" 