version: '3.9'
services:
  api:
    image: node:18-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: sh -c "cd apps/api && npm install && npm run dev"
    ports:
      - "3333:3000"
  web:
    image: node:18-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: sh -c "cd apps/web && npm install && npm run dev -- --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"

# Added for v0.2: MongoDB and Elasticsearch services
  mongodb:
    image: mongo:6.0
    container_name: golfergeek-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=golfergeek

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: golfergeek-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # Optional: Kibana for Elasticsearch management UI
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: golfergeek-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  mongodb_data:
  elasticsearch_data: 