FROM node:18-alpine AS builder

WORKDIR /app
COPY package.json turbo.json ./
COPY apps/web ./apps/web

RUN npm install
RUN npm run build --filter=web

FROM nginx:alpine AS runner
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 