FROM node:18-alpine AS builder

WORKDIR /app
COPY package.json turbo.json ./
COPY apps/api ./apps/api

RUN npm install
RUN npm run build --filter=api

FROM node:18-alpine AS runner
WORKDIR /app

COPY --from=builder /app/apps/api/package*.json ./
COPY --from=builder /app/apps/api/dist ./dist

RUN npm install --omit=dev

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["node", "dist/main.js"] 